### ISSUE TITLE
When will the neural architecture search code for SPVNAS released?

### ISSUE THREAD

**Issue by joonilna** [mit-han-lab/spvnas#15]
Hi! Thank you very much for a wonderful work.
I can't wait to try some experiments on SPVNAS.
In that matter, when will the neural architecture search code for SPVNAS release?
Thanks

**Comment by kentangSJTU** [comment]
Hi,

Sorry for the delayed response because I was working on an exam in the past two days. We are still transforming the search code from our old codebase to this one and testing its stability. I'll get back to you as soon as our search code is ready for release. At the current timestamp, I personally recommend you to have a try on our pretrained models and baseline training code, thanks!

Best,
Haotian

**Comment by joonil7** [comment]
Will Do! Thanks for the reply :)

**Comment by memoiry** [comment]
Could you suggest a timeline for the search code release? @kentangSJTU Thanks!

**Comment by kentangSJTU** [comment]
Hello @memoiry ,

I'm recently working on the journal version of SPVNAS. There will be some update on NAS in January 2021 after I finished the journal submission.

Best,
Haotian

**Comment by robot-ai-machinelearning** [comment]
Hi, Haotian:

@kentangSJTU Could you release the first draft version of your NAS code recently? I am trying to compare your methods to ours.

Thanks a lot!

Best,
Tiantian

**Comment by memoiry** [comment]
@kentangSJTU Hello, is there any update? It's already March...

**Comment by AllenPeng0209** [comment]
Hello, any update?

**Comment by knifeven** [comment]
Hello, 

I couldn't find the news of the released NAS anywhere.

is it not yet? 

or not, where did it release?

**Comment by xiaoaoran** [comment]
Hello, still waiting...

**Comment by sasasagagaga** [comment]
Hi! Do you have any updates on this issue?
