### ISSUE TITLE
How to train and evaluate spvnas model?

### ISSUE THREAD

**Issue by yukang2017** [mit-han-lab/spvnas#27]
Dear authors,

Thanks for your great work.
I notice that the training code only supports minkunet and spvcnn but not spvnas models (only minkunet and spvcnn in configs/semantic_kitti).
The evaluation code only supports to test your provided pretrained models.
How can we train and spvnas model? Thanks in advance.

Regards,
Chen Yukang

**Comment by kentangSJTU** [comment]
Hi Yukang,

The supernet training and NAS code will be released very soon after I finished some remaining work on the journal version of this paper. Please stay tuned and I will get back to you once this part is ready for release. Thanks!

Best,
Haotian

**Comment by ltriess** [comment]
I also want to train the SPVNAS model, but not the supernet training or NAS, just with the final architecture. As far as I can tell, this is not included in the code yet. However, it should work similar to the evaluation code but without loading the pretrained weights, right?
I understand that the network configuration can be found here [net.config](https://hanlab.mit.edu/files/SPVNAS/spvnas_specialized/SemanticKITTI_val_SPVNAS@65GMACs/net.config). Taking a look at `spvnas_specialized()` in `model_zoo.py`, I think it is possible to add another `elif` path in `make_model()` of `builder.py` for the defined SPVNAS model.
I tried to do it this way:
```
...
elif configs.model.name == "spvnas":
        from core.models.semantic_kitti import SPVNAS

        net_config = json.load(open("net.config"))

        model = SPVNAS(
            net_config["num_classes"],
            macro_depth_constraint=1,
            pres=net_config["pres"],
            vres=net_config["vres"],
        )
        model.manual_select(net_config)
else:
        ...
```
back in `train.py`
```
    model = torch.nn.parallel.DistributedDataParallel(
        model.cuda(), device_ids=[dist.local_rank()], find_unused_parameters=True
    )
```
is called on the model, therefore `model..to("cuda:%d" % dist.local_rank() if torch.cuda.is_available() else "cpu")` as in `model_zoo.py` is not necessary, correct? As far as I understood, the call `model.determinize()` is also only needed for forward pass modes. If I'm correct, in this case we do not need the call, since we want to network to be trained.

However, I encountered the problem that the training simply won't start and got stuck at `Epoch 1/15 started.`. Obviously, I am still doing something wrong. Can you tell from the information provided what I missed?
